# -------------------------------------------------------------------------------------------
# Deployment
# -------------------------------------------------------------------------------------------apiVersion: apps/v1

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    component: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: nginx
  # podの情報を定義
  template:
    metadata:
      labels:
        component: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
