# -------------------------------------------------------------------------------------------
# Service
# -------------------------------------------------------------------------------------------apiVersion: apps/v1

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx-service
  ports:
  - name: "nginx-port"
    protocol: "TCP"
    port: 8080
    targetPort: 80
    nodePort: 30080
