# -------------------------------------------------------------------------------------------
# Service
# -------------------------------------------------------------------------------------------apiVersion: apps/v1

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  # podを指定する
  selector:
    component: nginx
  ports:
  - name: "nginx-port"
    protocol: "TCP"
    port: 8080
    nodePort: 30080
    targetPort: 80
